### ISSUE TITLE
Get the mutational spectrum of a specified node and its descendants

### ISSUE THREAD

**Issue by szhan** [jeromekelleher/sc2ts#148]
[Bloom et al. (2023) MBE](https://academic.oup.com/mbe/advance-article/doi/10.1093/molbev/msad085/7113660) examined clade-specific mutational spectra. In Figure 1, they compared VoC-specific mutational spectra and noticed changes in mutational spectra (e.g., Omicron versus early clades).

It should be useful to extend the `get_mutation_spectrum` function in `sc2ts` to get the mutation spectrum of a clade under a specified ancestral node. We may also want to allow for including and/or excluding nested clades under nodes with certain metadata (e.g., GISAID clade or Pango lineage).

**Comment by jeromekelleher** [comment]
Good idea, that should be doable. I guess the straightforward way to do this for a single node is to iterate over the trees, and then look at all mutations at sites on that tree, and keep them if they have the node in question as an ancestor.

This will work fine for the application here I think, since we only care about a few important nodes. keeping the mutation spectrum for all nodes is harder, but doable I think
