### ISSUE TITLE
Add "Country_abbrev" to node metadata

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts#307]
When plotting out, it's very helpful to write "UK" rather than "United Kingdom". Can we add a "Country_abbrev" field that shortens at least the names UK and USA? It's tedious to do the replacements every time we want a plot.

**Comment by jeromekelleher** [comment]
I don't think it's worth doing this because we'd have to write a function that'll convert the country code for *everything* in the metadata, whereas we're likely to only every look at a handful. Adding this key to the metadata in the actual trees that we ship means that we should make it work properly, whereas if we have a quick function that does a mapping for our own viz needs we don't have to worry about quality.

It's hard to overstate the messiness of the metadata here, so it should be approached with great caution!
