### ISSUE TITLE
Record spike dropouts for QC

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts#48]
As suggested by @szhan

**Comment by szhan** [comment]
Amplicon dropouts have been a persistent problem with the ARTIC protocol since version 1. Unsurprisingly, it is still a problem in version 4 (https://www.medrxiv.org/content/10.1101/2022.12.01.22282842v1). Knowledge about where in the genome and in which variants amplicon dropouts frequently happen may help with QC and diagnosing issues in ARG building.
